# permissions for end users to view prompts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: prompt-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: llm-operator
    app.kubernetes.io/part-of: llm-operator
    app.kubernetes.io/managed-by: kustomize
  name: prompt-viewer-role
rules:
- apiGroups:
  - base.fleezesd.io
  resources:
  - prompts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - base.fleezesd.io
  resources:
  - prompts/status
  verbs:
  - get
