---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - base.fleezesd.io
  resources:
  - llms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - base.fleezesd.io
  resources:
  - llms/finalizers
  verbs:
  - update
- apiGroups:
  - base.fleezesd.io
  resources:
  - llms/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - base.fleezesd.io
  resources:
  - models
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - base.fleezesd.io
  resources:
  - models/finalizers
  verbs:
  - update
- apiGroups:
  - base.fleezesd.io
  resources:
  - models/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - base.fleezesd.io
  resources:
  - prompts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - base.fleezesd.io
  resources:
  - prompts/finalizers
  verbs:
  - update
- apiGroups:
  - base.fleezesd.io
  resources:
  - prompts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - base.fleezesd.io
  resources:
  - workers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - base.fleezesd.io
  resources:
  - workers/finalizers
  verbs:
  - update
- apiGroups:
  - base.fleezesd.io
  resources:
  - workers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - llm.fleezesd.io
  resources:
  - models
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - llm.fleezesd.io
  resources:
  - models/finalizers
  verbs:
  - update
- apiGroups:
  - llm.fleezesd.io
  resources:
  - models/status
  verbs:
  - get
  - patch
  - update
